### ISSUE TITLE
Flexible locating .proto files

### ISSUE THREAD

**Issue by peter-lyons-kehl** [marcoferrer/kotlin-coroutines-gRPC-template#2]
Dear Marco,

Thank you for Kroto+ and this template.

I'm new to most of these technologies: Kotlin, Gradle, Protobuf. So advance apologies if I've missed the obvious. If you can give any suggestions, I'm willing to add them to `README.md` and provide pull requests. That would save time for you and others.

Can we specify where to find `.proto` files. And/or is there a way to process only some `.proto` files, not all of them? A project could have several clones of the coroutine template. Each template would pick some of shared `.proto` files.

Of course, I can workaround with `.proto` being symlinked. However, that may confuse people. Also, it doesn't work for my peers on Windows.

**Comment by marcoferrer** [comment]
Usually the selection of which proto files to compile is managed by the configuration type in gradle.  (compile vs. compileOnly vs. protobuf). Which template it is that you were using that gave you issues?

**Comment by peter-lyons-kehl** [comment]
I use the `master` branch of this repo. That's about all I know about its configuration - I don't know which one of `compile`, `compileOnly` or `protobuf` it uses. In `api/build.gradle` I see `protobuf` - is that what indicates the configuration type, or where?

The project is a standard Gradle subproject, in folder `kotlin-template/common`. The parent `settings.gradle` has `include ':kotlin-template:common', ':kotlin-template:common:api'`.

The only differences between my subproject and your master are:
```
allprojects {
    // Using a relative path for the following failed. Hence using $rootDir
    apply from: "$rootDir/gradle/common/repository.gradle"
    ...

dependencies {
   ...    
    implementation project(':kotlin-template:common:api')
```

But how can one make it collect other (additional) `.proto` files outside of this (sub)project's folder, please?

**Comment by marcoferrer** [comment]
The configuration for additional sources is documented here in the protobuf gradle repo (including examples).
https://github.com/google/protobuf-gradle-plugin#customizing-source-directories

Let me know if this is what you meant.

**Comment by peter-lyons-kehl** [comment]
Thank you for the pointer. That helped.
